### ISSUE TITLE
Updating swoole version

### ISSUE THREAD

**Issue by foremtehan** [cachewerk/heroku-php-extensions#13]
the swoole version stuck in 4.8.3 but i set it as `"ext-swoole": "*",` @tillkruss the swoole team [added ](https://github.com/swoole/swoole-src/pull/4467)async i/o support for postgres driver, Can you upgrade it to the lastest version (v4.8.6) in heroku? i'd really appreciated thanks!

**Comment by tillkruss** [comment]
Do you want to submit a PR for the lastest release?

**Comment by foremtehan** [comment]
Honestly I never worked with pecl extension.

Heroku uses this file https://relaycache.com/heroku/packages.json to download extensions which i unable to modify...

**Comment by foremtehan** [comment]
Looks like they dont released it yet https://github.com/swoole/swoole-src/issues/4573

So i think we should waiting for now, I'll tag you

**Comment by tillkruss** [comment]
Ok 👍
