### ISSUE TITLE
Can ext-openswoole be supported?

### ISSUE THREAD

**Issue by kingIZZZY** [cachewerk/heroku-php-extensions#17]
👆

**Comment by tillkruss** [comment]
Yes, feel free to open a PR.

**Comment by kingIZZZY** [comment]
Personally have no clue how enabling these extensions for Heroku works - could it be just as simple as editing some config/build files to do "openswoole" instead of "swoole" ? Or it's (probably..) more complicated than that...

**Comment by kingIZZZY** [comment]
Similar question for the recently released ext-swoole (not openswoole) version 5.0.0

**Comment by tillkruss** [comment]
`ext-openswoole` needs to be added separately from `ext-swoole`

**Comment by kingIZZZY** [comment]
I can try to just clone the repo and mess around with whatever I can find, I'm just preemptively not sure what i'm doing - maybe I'm missing some important big step such as "have Ubuntu 22 and build the entire openswoole from source" or something... but oh well I can try giving it a try

**Comment by tillkruss** [comment]
You'll first want to add openswoole before adding Heroku-22.

**Comment by kingIZZZY** [comment]
For example - can I just follow the same actions as commit # https://github.com/cachewerk/heroku-php-extensions/commit/fb41db3e75d77d3c76dd2d8ebcabfd4b9094bb79 to update ext-swoole to 5.0.0? That _seems_ like a simple starting point to try my hands at any of this... oh well let's try and see 🤷‍♂️

**Comment by kingIZZZY** [comment]
Alright here comes nothing https://github.com/cachewerk/heroku-php-extensions/pull/18

Now, how do do similar idea for supporting openswoole....

**Comment by kingIZZZY** [comment]
Alright here goes nothing #19 

Next step - another PR to add support for openswoole...

**Comment by kingIZZZY** [comment]
And there goes another nothing #20

Next step - where to even begin about supporting heroku-22 stack?...

**Comment by tillkruss** [comment]
This is now building.
