### ISSUE TITLE
Using the "https://relay.so/heroku/" platform repository returns error.

### ISSUE THREAD

**Issue by romek-dev** [cachewerk/heroku-php-extensions#31]
## Description
It seems something broke, i can't build on heroku anymore and keep getting an error. 
Your demo app is also no longer working, could be the same issue.

## Expected Behavior

My App builds successfully without any errors.

## Actual Behavior
```
 !     > Loading repositories with available runtimes and extensions
 !     > Warning: the packages key '0' doesn't match the name defined in the package metadata 'ext-igbinary' in repository https://relay.so/heroku
 !     > Updating dependencies
 !     > Your requirements could not be resolved to an installable set of packages.
 !     > 
 !     >   Problem 1
 !     >     - ext-swoole[4.6.4, ..., 4.8.12, 5.0.0] require heroku ^18.0.0 -> could not be found in any version, but the following packages provide it:
 !     >       - __root__
 !     >       Consider requiring one of these to satisfy the heroku requirement.
 !     >     - composer.json/composer.lock requires ext-swoole * -> satisfiable by ext-swoole[4.6.4, ..., 4.8.12, 5.0.0].
 !     > 
 ```

## Possible Fix
I fixed it by using:
heroku config:set HEROKU_PHP_PLATFORM_REPOSITORIES="https://heroku-php-extensions.s3.amazonaws.com/dist-heroku-22-stable/"

instead of:
heroku config:set HEROKU_PHP_PLATFORM_REPOSITORIES="https://relay.so/heroku/"

but before the latest release relay.so was working.

## Steps to Reproduce
1. Just try deploying.

## Additional context

Release new development build

## Environment
* OS and version: Ubuntu-22 (heroku-20 and heroku-22 both don't work)
* PHP version: 8.1, 8.2 and 8.3 don't work.

**Comment by tillkruss** [comment]
Ah, yes, the Heroku controller was still using 18, and didn't include 22. That will be fixed shortly.
