### ISSUE TITLE
composer require "ext-swoole:*"

### ISSUE THREAD

**Issue by vs0uz4** [cachewerk/heroku-php-extensions#7]
Compose package not find.
![Captura de tela de 2021-04-17 13-54-05](https://user-images.githubusercontent.com/2080547/115120566-82916c00-9f84-11eb-8d3e-afc74cabc982.png)

composer require "ext-pcntl:*" its OK, swoole not found!

**Comment by tillkruss** [comment]
What does `heroku config:set HEROKU_PHP_PLATFORM_REPOSITORIES` show? As well as `heroku stack`?
