### ISSUE TITLE
Swoole version 4.6.6 ?

### ISSUE THREAD

**Issue by kingIZZZY** [cachewerk/heroku-php-extensions#8]
Just checking heartbeat / pulse on this project, are you able to regularly update it?
How soon might we be able to see latest Swoole versions when they come out, ex. as of writing: 4.6.6

**Comment by tillkruss** [comment]
You can submit a PR, should be pretty straight forward and we can release new versions instantly 👍

**Comment by tillkruss** [comment]
See 3e2a27ab78dd015f08ddda2b258cf2f279f80914.
